import {
  nextProblems,
  STATUSES,
  STRUCTURE_KINDS,
  type Roadmap,
  type RoadmapProblem,
  type Status,
} from './schema.js'

const GENERATED_HEADER = '<!-- GENERATED by `pnpm roadmap:generate` — do not edit by hand. -->'

const STATUS_ICON: Record<Status, string> = {
  todo: '⬜',
  'in-progress': '🟡',
  review: '🔵',
  blocked: '🔴',
  done: '✅',
}

function bar(done: number, total: number, width = 28): string {
  const filled = total === 0 ? 0 : Math.round((done / total) * width)
  return `${'█'.repeat(filled)}${'░'.repeat(width - filled)}`
}

function prCell(p: RoadmapProblem): string {
  if (p.pr === null) return '—'
  return typeof p.pr === 'number' ? `#${p.pr}` : p.pr
}

/**
 * Render ROADMAP.md from the roadmap data. Pure — takes data, returns a string — so it can be
 * golden-tested and so `roadmap:check` can diff it against disk without touching the file.
 */
export function renderMarkdown(roadmap: Roadmap): string {
  const total = roadmap.problems.length
  const done = roadmap.problems.filter((p) => p.status === 'done').length
  const pct = total === 0 ? 0 : Math.round((done / total) * 100)

  const out: string[] = [
    GENERATED_HEADER,
    '',
    '# AlgoViz Roadmap — LeetCode 75',
    '',
    'Every problem here is solved *inside the app*: you write the instrumented solution and',
    'watch your own algorithm execute over a live visualization of the structures it touches.',
    '',
    `**Progress: ${done} / ${total} done (${pct}%)**`,
    '',
    `\`${bar(done, total)}\``,
    '',
  ]

  // Status summary
  const counts = new Map<Status, number>()
  for (const s of STATUSES) counts.set(s, 0)
  for (const p of roadmap.problems) counts.set(p.status, (counts.get(p.status) ?? 0) + 1)
  out.push(
    '| Status | Count |',
    '| --- | --- |',
    ...STATUSES.map((s) => `| ${STATUS_ICON[s]} ${s} | ${counts.get(s) ?? 0} |`),
    '',
  )

  // Next up — same function the MCP `roadmap_next` tool uses, so the doc can't disagree.
  const next = nextProblems(roadmap, 3)
  if (next.length > 0) {
    out.push('## Next up', '')
    for (const p of next) {
      out.push(`1. **${p.leetcode}. ${p.title}** — ${p.difficulty}, ${p.category} (\`${p.structures.join(', ')}\`)`)
    }
    out.push('', 'Run the `solve-problem` skill to take the next one end to end.', '')
  }

  // Per-category tables
  out.push('## Problems by category', '')
  const sortedCategories = [...roadmap.categories].sort((a, b) => a.order - b.order)
  for (const category of sortedCategories) {
    const problems = roadmap.problems
      .filter((p) => p.category === category.id)
      .sort((a, b) => a.order - b.order)
    if (problems.length === 0) continue
    const catDone = problems.filter((p) => p.status === 'done').length
    out.push(
      `### ${category.title} — ${catDone}/${problems.length}`,
      '',
      '| # | Problem | Difficulty | Structures | Status | PR |',
      '| --- | --- | --- | --- | --- | --- |',
    )
    for (const p of problems) {
      const link = `[${p.title}](https://leetcode.com/problems/${p.slug}/)`
      out.push(
        `| ${p.leetcode} | ${link} | ${p.difficulty} | \`${p.structures.join(', ')}\` | ${STATUS_ICON[p.status]} ${p.status} | ${prCell(p)} |`,
      )
    }
    out.push('')
  }

  // Structure coverage — surfaces "we have never actually animated a trie" early.
  out.push(
    '## Visualizer coverage',
    '',
    'How many *done* problems exercise each tracked structure. A zero here means that',
    'visualizer has no real user yet, however green its unit tests are.',
    '',
    '| Structure | Done | Planned |',
    '| --- | --- | --- |',
  )
  for (const kind of STRUCTURE_KINDS) {
    const planned = roadmap.problems.filter((p) => p.structures.includes(kind))
    const coveredBy = planned.filter((p) => p.status === 'done').length
    out.push(`| \`${kind}\` | ${coveredBy} | ${planned.length} |`)
  }
  out.push('')

  return out.join('\n')
}

export const ROADMAP_GENERATED_HEADER = GENERATED_HEADER
