import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { renderMarkdown } from './generate.js'
import { findRepoRoot, loadRoadmap, roadmapMarkdownPath } from './load.js'
import { parseRoadmap, RoadmapError } from './parse.js'
import { nextProblems, STRUCTURE_KINDS, validateRoadmap, type Roadmap } from './schema.js'

const repoRoot = findRepoRoot()

function base(problems: Partial<Roadmap['problems'][number]>[]): Roadmap {
  return {
    version: 1,
    set: 'test',
    categories: [{ id: 'cat', title: 'Cat', order: 1 }],
    problems: problems.map((p, i) => ({
      id: p.id ?? `p${String(i + 1).padStart(3, '0')}`,
      leetcode: p.leetcode ?? i + 1,
      title: p.title ?? `Problem ${i + 1}`,
      slug: p.slug ?? `problem-${i + 1}`,
      difficulty: p.difficulty ?? 'easy',
      category: p.category ?? 'cat',
      order: p.order ?? i + 1,
      structures: p.structures ?? ['array'],
      techniques: p.techniques ?? [],
      status: p.status ?? 'todo',
      branch: p.branch ?? null,
      pr: p.pr ?? null,
      notes: p.notes ?? null,
      dependsOn: p.dependsOn ?? [],
    })),
  }
}

describe('the real roadmap.yaml', () => {
  const roadmap = loadRoadmap()

  it('contains the full LeetCode 75 set across 22 categories', () => {
    expect(roadmap.problems).toHaveLength(75)
    expect(roadmap.categories).toHaveLength(22)
    expect(roadmap.set).toBe('leetcode-75')
  })

  it('passes every integrity check', () => {
    expect(validateRoadmap(roadmap)).toEqual([])
  })

  it('gives every problem a category that exists', () => {
    const ids = new Set(roadmap.categories.map((c) => c.id))
    for (const p of roadmap.problems) expect(ids, p.id).toContain(p.category)
  })

  it('declares only structures the tracer can actually render', () => {
    for (const p of roadmap.problems) {
      for (const s of p.structures) expect(STRUCTURE_KINDS, `${p.id} declares ${s}`).toContain(s)
    }
  })

  it('has contiguous order values from 1..75', () => {
    const orders = roadmap.problems.map((p) => p.order).sort((a, b) => a - b)
    expect(orders).toEqual(Array.from({ length: 75 }, (_, i) => i + 1))
  })

  it('plans at least one problem for every structure kind', () => {
    // Otherwise a visualizer would ship with no real user, however green its unit tests are.
    for (const kind of STRUCTURE_KINDS) {
      const planned = roadmap.problems.filter((p) => p.structures.includes(kind))
      expect(planned.length, `no problem exercises "${kind}"`).toBeGreaterThan(0)
    }
  })
})

describe('ROADMAP.md', () => {
  it('is in sync with roadmap.yaml', () => {
    // Mirrors `pnpm roadmap:check`, so staleness fails in the local test run too.
    const onDisk = readFileSync(roadmapMarkdownPath(repoRoot), 'utf8')
    expect(onDisk).toBe(renderMarkdown(loadRoadmap()))
  })
})

describe('renderMarkdown', () => {
  it('reports progress, per-category counts and coverage', () => {
    const md = renderMarkdown(
      base([
        { id: 'p001', status: 'done', branch: 'b', structures: ['array'] },
        { id: 'p002', status: 'todo', structures: ['graph'] },
      ]),
    )
    expect(md).toContain('**Progress: 1 / 2 done (50%)**')
    expect(md).toContain('### Cat — 1/2')
    expect(md).toMatch(/\| `array` \| 1 \| 1 \|/)
    expect(md).toMatch(/\| `graph` \| 0 \| 1 \|/)
  })

  it('starts with the do-not-edit header', () => {
    expect(renderMarkdown(base([{}]))).toMatch(/^<!-- GENERATED by/)
  })
})

describe('nextProblems', () => {
  it('skips done and blocked entries and respects order', () => {
    const roadmap = base([
      { id: 'p001', status: 'done', branch: 'b', order: 1 },
      { id: 'p002', status: 'blocked', order: 2 },
      { id: 'p003', status: 'todo', order: 3 },
      { id: 'p004', status: 'todo', order: 4 },
    ])
    expect(nextProblems(roadmap, 2).map((p) => p.id)).toEqual(['p003', 'p004'])
  })

  it('holds back a problem whose dependency is not done', () => {
    const roadmap = base([
      { id: 'p001', status: 'todo', order: 1 },
      { id: 'p002', status: 'todo', order: 2, dependsOn: ['p001'] },
    ])
    expect(nextProblems(roadmap, 5).map((p) => p.id)).toEqual(['p001'])
  })

  it('releases a problem once its dependency is done', () => {
    const roadmap = base([
      { id: 'p001', status: 'done', branch: 'b', order: 1 },
      { id: 'p002', status: 'todo', order: 2, dependsOn: ['p001'] },
    ])
    expect(nextProblems(roadmap, 5).map((p) => p.id)).toEqual(['p002'])
  })
})

describe('validateRoadmap', () => {
  it('flags duplicate ids, slugs, numbers and orders', () => {
    const roadmap = base([
      { id: 'p001', slug: 'same', leetcode: 7, order: 1 },
      { id: 'p001', slug: 'same', leetcode: 7, order: 1 },
    ])
    const messages = validateRoadmap(roadmap).map((i) => i.message)
    expect(messages).toContain('duplicate id: p001')
    expect(messages).toContain('duplicate slug: same')
    expect(messages).toContain('duplicate leetcode: 7')
    expect(messages).toContain('duplicate order: 1')
  })

  it('flags an unknown category', () => {
    const roadmap = base([{ category: 'nope' }])
    expect(validateRoadmap(roadmap)[0]?.message).toContain('unknown category')
  })

  it('flags a done problem with nothing to point at', () => {
    const roadmap = base([{ status: 'done' }])
    expect(validateRoadmap(roadmap)[0]?.message).toContain('neither pr nor branch')
  })

  it('flags an unresolvable dependency', () => {
    const roadmap = base([{ dependsOn: ['pXXX'] }])
    expect(validateRoadmap(roadmap)[0]?.message).toContain('unknown problem')
  })

  it('detects a dependency cycle', () => {
    const roadmap = base([
      { id: 'p001', dependsOn: ['p002'] },
      { id: 'p002', dependsOn: ['p001'] },
    ])
    expect(validateRoadmap(roadmap).some((i) => i.message === 'dependency cycle')).toBe(true)
  })
})

describe('parseRoadmap', () => {
  it('rejects a malformed slug with a readable message', () => {
    expect(() =>
      parseRoadmap(`
version: 1
set: t
categories: [{ id: cat, title: Cat, order: 1 }]
problems:
  - id: p001
    leetcode: 1
    title: T
    slug: Not_Kebab
    difficulty: easy
    category: cat
    order: 1
    structures: [array]
    status: todo
`),
    ).toThrow(/kebab-case/)
  })

  it('rejects an unknown structure kind', () => {
    expect(() =>
      parseRoadmap(`
version: 1
set: t
categories: [{ id: cat, title: Cat, order: 1 }]
problems:
  - id: p001
    leetcode: 1
    title: T
    slug: t
    difficulty: easy
    category: cat
    order: 1
    structures: [quantum-foam]
    status: todo
`),
    ).toThrow(RoadmapError)
  })
})
